/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './index';
import * as import2 from '@angular/core/src/di/injector';
class FusionChartsModuleInjector extends import0.NgModuleInjector<import1.FusionChartsModule> {
  _FusionChartsModule_0:import1.FusionChartsModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.FusionChartsModule {
    this._FusionChartsModule_0 = new import1.FusionChartsModule();
    return this._FusionChartsModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.FusionChartsModule)) { return this._FusionChartsModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const FusionChartsModuleNgFactory:import0.NgModuleFactory<import1.FusionChartsModule> = new import0.NgModuleFactory(FusionChartsModuleInjector,import1.FusionChartsModule);