let importCode = `import { NgModule } from '@angular/core';\nimport { BrowserModule } from '@angular/platform-browser';\n\n// Import angular-fusioncharts\nimport { FusionChartsModule } from 'angular-fusioncharts';\n\n// Import FusionCharts library\nimport * as FusionCharts from 'fusioncharts';\n\n// Load FusionCharts Individual Charts\nimport * as Charts from 'fusioncharts/fusioncharts.charts';\n// Add other dependecies like Charts, PowerCharts, Widgets, Maps\n// import FusionTheme from 'fusioncharts/themes/fusioncharts.theme.fusion';\n// import Maps from 'fusioncharts/fusioncharts.maps';\n// import World from 'fusioncharts/maps/fusioncharts.world';\n\n\n\n// Use fcRoot function to inject FusionCharts library, and the modules \n// you want to use\n//FusionChartsModule.fcRoot(FusionCharts, [Comma separated charts and features]) \nFusionChartsModule.fcRoot(FusionCharts, Charts)\n\n@NgModule({\n  declarations: [\n    AppComponent\n  ],\n  imports: [\n    BrowserModule,\n    FusionChartsModule // Include in imports\n  ],\n  bootstrap: [AppComponent]\n})\nexport class AppModule { }`;
let installCode = '$ npm install angular-fusioncharts --save';
let installFusionCharts = '$ npm install fusioncharts --save';
let useDirective = `import { Component } from '@angular/core';\n\n@Component({\n    selector: 'my-app',\n    template: \`<fusioncharts\n      width="500" \n      height="300"\n      type="column2d"\n      dataFormat="json"\n      [dataSource]="data" >\n    </fusioncharts>\n  \`,\n})\nexport class AppComponent {\n  data: Object;\n  \n  constructor() {\n    this.data = {\n      chart: { },\n      data: [\n        {value: 500},\n        {value: 600},\n        {value: 700}\n      ]\n    };\n  }\n}`;
let renderFusionMaps = `import { NgModule } from '@angular/core';\nimport { BrowserModule } from '@angular/platform-browser';\nimport { AppComponent } from './app.component';\n\n// Import FusionChartsModule from angular-fusioncharts\nimport { FusionChartsModule } from 'angular-fusioncharts';\n\n// Import FusionCharts library\nimport * as FusionCharts from 'fusioncharts';\n\n\n// Load FusionCharts Maps module\nimport * as Maps from 'fusioncharts/fusioncharts.maps';\n\n// Load WorldMap map definition module\nimport * as World from 'fusioncharts/maps/fusioncharts.world';\n\n// Use FusionChartsModule.fcRoot(FusionCharts, [Comma separated modules])\nFusionChartsModule.fcRoot(FusionCharts, Maps, World)\n\n@NgModule({\n  declarations: [\n    AppComponent\n  ],\n  imports: [\n    BrowserModule, \n    FusionChartsModule // Include in the imports\n  ],\n  bootstrap: [AppComponent]\n})\nexport class AppModule { }`;
let mapHtml = `<!-- in app.component.html -->\n<fusioncharts\n type="world"\n width="800"\n height="500"\n dataFormat="json">\n</fusioncharts>`;
let setupFusionTime = `// app.module.ts\nimport { BrowserModule } from '@angular/platform-browser';\nimport { NgModule } from '@angular/core';\nimport { AppComponent } from './app.component';\n// Import angular-fusioncharts\nimport { FusionChartsModule } from 'angular-fusioncharts';\n// Import FusionCharts library and chart modules\nimport * as FusionCharts from 'fusioncharts';\nimport * as Charts from 'fusioncharts/fusioncharts.charts';\nimport * as TimeSeries from 'fusioncharts/fusioncharts.timeseries'; // Import timeseries\n// Pass the fusioncharts library and chart modules\nFusionChartsModule.fcRoot(FusionCharts, Charts, TimeSeries);\n@NgModule({\n  declarations: [AppComponent],\n  imports: [\n    BrowserModule,\n    // Specify FusionChartsModule as import\n    FusionChartsModule\n  ],\n  providers: [],\n  bootstrap: [AppComponent]\n})\nexport class AppModule {}`;
let fusionTimeComponentCode = `// In app.component.ts\nimport { Component } from '@angular/core';\nimport * as FusionCharts from 'fusioncharts';\nconst dataUrl =\n  'https://raw.githubusercontent.com/fusioncharts/dev_centre_docs/master/assets/datasources/fusiontime/online-sales-single-series-area-data-plot/data.json';\nconst schemaUrl =\n  'https://raw.githubusercontent.com/fusioncharts/dev_centre_docs/master/assets/datasources/fusiontime/online-sales-single-series-area-data-plot/schema.json';\n@Component({\n  selector: 'app',\n  templateUrl: './app.component.html'\n})\nexport class AppComponent {\n  dataSource: any;\n  type: string;\n  width: string;\n  height: string;\n  constructor() {\n    this.type = 'timeseries';\n    this.width = '400';\n    this.height = '400';\n    this.dataSource = {\n      data: null,\n      yAxis: {\n        plot: [{ value: 'Sales' }]\n      },\n      caption: {\n        text: 'Online Sales of a SuperStore in the US'\n      }\n    };\n    this.fetchData();\n  }\n  fetchData() {\n    let jsonify = res => res.json();\n    let dataFetch = fetch(dataUrl).then(jsonify);\n    let schemaFetch = fetch(schemaUrl).then(jsonify);\n    Promise.all([dataFetch, schemaFetch]).then(res => {\n      let data = res[0];\n      let schema = res[1];\n      let fusionTable = new FusionCharts.DataStore().createDataTable(\n        data,\n        schema\n      ); // Instance of DataTable to be passed as data in dataSource\n      this.dataSource.data = fusionTable;\n    });\n  }\n}`;
let fusionTimeTemplateCode = `<div>\n  <fusioncharts\n    [type]="type"\n    [width]="width"\n    [height]="height"\n    [dataSource]="dataSource"\n  ></fusioncharts>\n</div>`;

export default {
  importCode,
  installCode,
  installFusionCharts,
  useDirective,
  renderFusionMaps,
  mapHtml,
  setupFusionTime,
  fusionTimeComponentCode,
  fusionTimeTemplateCode
};
