let importCode = `import { NgModule } from '@angular/core';\nimport { BrowserModule } from '@angular/platform-browser';\n\n// Import angular-fusioncharts\nimport { FusionChartsModule } from 'angular-fusioncharts';\n\n// Import FusionCharts library\nimport * as FusionCharts from 'fusioncharts';\n\n// Load FusionCharts Individual Charts\nimport * as Charts from 'fusioncharts/fusioncharts.charts';\n// Add other dependecies like Charts, PowerCharts, Widgets, Maps\n// import FusionTheme from 'fusioncharts/themes/fusioncharts.theme.fusion';\n// import Maps from 'fusioncharts/fusioncharts.maps';\n// import World from 'fusioncharts/maps/fusioncharts.world';\n\n\n\n// Use fcRoot function to inject FusionCharts library, and the modules \n// you want to use\n//FusionChartsModule.fcRoot(FusionCharts, [Comma separated charts and features]) \nFusionChartsModule.fcRoot(FusionCharts, Charts)\n\n@NgModule({\n  declarations: [\n    AppComponent\n  ],\n  imports: [\n    BrowserModule,\n    FusionChartsModule // Include in imports\n  ],\n  bootstrap: [AppComponent]\n})\nexport class AppModule { }`;
let installCode = '$ npm install angular-fusioncharts --save';
let installFusionCharts = '$ npm install fusioncharts --save';
let useDirective = `import { Component } from '@angular/core';\n\n@Component({\n    selector: 'my-app',\n    template: \`<fusioncharts\n      width="500" \n      height="300"\n      type="column2d"\n      dataFormat="json"\n      [dataSource]="data" >\n    </fusioncharts>\n  \`,\n})\nexport class AppComponent {\n  data: Object;\n  \n  constructor() {\n    this.data = {\n      chart: { },\n      data: [\n        {value: 500},\n        {value: 600},\n        {value: 700}\n      ]\n    };\n  }\n}`;
let renderFusionMaps = `import { NgModule } from '@angular/core';\nimport { BrowserModule } from '@angular/platform-browser';\nimport { AppComponent } from './app.component';\n\n// Import FusionChartsModule from angular-fusioncharts\nimport { FusionChartsModule } from 'angular-fusioncharts';\n\n// Import FusionCharts library\nimport * as FusionCharts from 'fusioncharts';\n\n\n// Load FusionCharts Maps module\nimport * as Maps from 'fusioncharts/fusioncharts.maps';\n\n// Load WorldMap map definition module\nimport * as World from 'fusioncharts/maps/fusioncharts.world';\n\n// Use FusionChartsModule.fcRoot(FusionCharts, [Comma separated modules])\nFusionChartsModule.fcRoot(FusionCharts, Maps, World)\n\n@NgModule({\n  declarations: [\n    AppComponent\n  ],\n  imports: [\n    BrowserModule, \n    FusionChartsModule // Include in the imports\n  ],\n  bootstrap: [AppComponent]\n})\nexport class AppModule { }`;
let mapHtml = `<!-- in app.component.html -->\n<fusioncharts\n type="world"\n width="800"\n height="500"\n dataFormat="json">\n</fusioncharts>`;
export default {
  importCode,
  installCode,
  installFusionCharts,
  useDirective,
  renderFusionMaps,
  mapHtml
}